<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HPLicenseTool</RootNamespace>
    <AssemblyName>HPLicenseTool</AssemblyName>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhuXuanParkingSystem.Domain\PhuXuanParkingSystem.Domain.csproj" />
  </ItemGroup>

</Project>
